<?= '<?php' ?>

/**
 * This file is auto-generated by PhpCocktail to help IDEs understand code where namespaces classes get dinamicly
 * 	shifted to root namespace.
 * It shall not be run at all, this the die.
 */

die('This file is not intended to be run.');

